name: eloquim_flutter
description: A new way to communicate using emojis.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: "^3.8.0"
  flutter: "^3.32.0"

dependencies:
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.5
  flutter:
    sdk: flutter
  eloquim_client:
    path: ../eloquim_client
  serverpod_flutter: 3.2.2
  serverpod_auth_idp_flutter: 3.2.2
  flutter_riverpod: ^3.2.0
  genui: ^0.6.1
  genui_firebase_ai: ^0.6.1
  go_router: ^17.0.1
  shared_preferences: ^2.5.4
  serverpod_auth_shared_flutter: ^3.2.2
  firebase_core: ^4.4.0
  firebase_ai: ^3.7.0

dev_dependencies:
  change_app_package_name: ^1.5.0
  flutter_launcher_icons: ^0.14.4
  flutter_lints: ">=3.0.0 <7.0.0"
  flutter_native_splash: ^2.4.7
  flutter_test:
    sdk: flutter
    # To launch run: dart run flutter_native_splash:create
    # To launch run: dart run flutter_launcher_icons
flutter_launcher_icons:
  image_path: "assets/images/eloquim_logo.jpg"
  adaptive_icon_background: "#212121"
  adaptive_icon_foreground: "assets/images/eloquim_logo.jpg"
  android: true
  ios: true
  min_sdk_android: 21
  web:
    generate: true
    image_path: "assets/images/eloquim_logo.jpg"
flutter_native_splash:
  color: "#212121"
  image: "assets/images/eloquim_logo.jpg"
# The following section is specific to Flutter.
flutter:
  uses-material-design: true

  assets:
    - assets/config.json
    - assets/images/
dependency_overrides:
  flutter_secure_storage: ^10.0.0

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
