name: Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      VERSION: '3.2.2'
      SERVERPOD_PASSWORD_database: 'uZbz5vz2VG0ckA54tDt1t5PMkvL5qMIg'
      SERVERPOD_PASSWORD_redis: '_DWDBmyL_4HJ2RfNDsdHLnrHLc5uw2_K'

    steps:
      - uses: actions/checkout@v4

      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.32.8'

      - name: Start containers
        working-directory: eloquim_server
        run: docker compose up --build -d

      - name: Install dependencies
        working-directory: eloquim_server
        run: dart pub get

      - name: Install Serverpod CLI
        working-directory: eloquim_server
        run: dart pub global activate serverpod_cli $VERSION

      - name: Run Serverpod generator
        working-directory: eloquim_server
        run: serverpod generate

      - name: Run tests
        working-directory: eloquim_server
        run: dart test

      - name: Stop containers
        if: always()
        working-directory: eloquim_server
        run: docker compose down -v
